version: "3.9"
services:
  goods:
    image: postgres:16.0
    container_name: goods-container
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - goods-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  goods-volume: