insert into goods (id, name, description, price, in_stock) values (1, 'Jaquenette', 'Murazik Group', 48877, true);
insert into goods (id, name, description, price, in_stock) values (2, 'Xena', 'Ankunding Inc', 28389, false);
insert into goods (id, name, description, price, in_stock) values (3, 'Abagael', 'Glover-Kunze', 19421, false);
insert into goods (id, name, description, price, in_stock) values (4, 'Aryn', 'Conn Inc', 69252, false);
insert into goods (id, name, description, price, in_stock) values (5, 'Saraann', 'Hoeger, Hauck and Larkin', 50639, true);
insert into goods (id, name, description, price, in_stock) values (6, 'Koressa', 'Grant-Davis', 87205, true);
insert into goods (id, name, description, price, in_stock) values (7, 'Jeana', 'Stoltenberg, Prosacco and Glover', 29283, true);
insert into goods (id, name, description, price, in_stock) values (8, 'Gussie', 'Von, Denesik and Hodkiewicz', 26047, true);
insert into goods (id, name, description, price, in_stock) values (9, 'Harriott', 'Hegmann, Wiegand and Steuber', 80939, true);
insert into goods (id, name, description, price, in_stock) values (10, 'Stephani', 'Will and Sons', 51218, false);
insert into goods (id, name, description, price, in_stock) values (11, 'Theodora', 'Schaefer-Pollich', 90074, true);
insert into goods (id, name, description, price, in_stock) values (12, 'Dierdre', 'Collins, Morissette and Beatty', 96146, true);
insert into goods (id, name, description, price, in_stock) values (13, 'Brynne', 'Johns, Weber and Rodriguez', 83061, false);
insert into goods (id, name, description, price, in_stock) values (14, 'Karla', 'Lynch LLC', 27726, true);
insert into goods (id, name, description, price, in_stock) values (15, 'Del', 'Luettgen, Rowe and Nader', 6440, false);
insert into goods (id, name, description, price, in_stock) values (16, 'Dot', 'Heidenreich-Rolfson', 92634, true);
insert into goods (id, name, description, price, in_stock) values (17, 'Christen', 'Hirthe-Lockman', 32971, false);
insert into goods (id, name, description, price, in_stock) values (18, 'Bianca', 'Bins-Dach', 22184, false);
insert into goods (id, name, description, price, in_stock) values (19, 'Karissa', 'Block-Satterfield', 65483, true);
insert into goods (id, name, description, price, in_stock) values (20, 'Lola', 'Mitchell-Rippin', 96832, true);
insert into goods (id, name, description, price, in_stock) values (21, 'Rosene', 'Murazik, Abshire and Yundt', 49331, true);
insert into goods (id, name, description, price, in_stock) values (22, 'Elinor', 'Cassin, Frami and Treutel', 53479, true);
insert into goods (id, name, description, price, in_stock) values (23, 'Sascha', 'Kuhn-Marquardt', 43528, true);
insert into goods (id, name, description, price, in_stock) values (24, 'Lil', 'Bernhard and Sons', 979, true);
insert into goods (id, name, description, price, in_stock) values (25, 'Bamby', 'Kuvalis Group', 45779, false);
insert into goods (id, name, description, price, in_stock) values (26, 'Moyra', 'Mayert-O''Keefe', 9413, true);
insert into goods (id, name, description, price, in_stock) values (27, 'Gloriana', 'Johns-Goldner', 2494, false);
insert into goods (id, name, description, price, in_stock) values (28, 'Emmaline', 'Waelchi Inc', 81179, false);
insert into goods (id, name, description, price, in_stock) values (29, 'Beilul', 'Murazik, Murray and Wisoky', 56690, true);
insert into goods (id, name, description, price, in_stock) values (30, 'Karly', 'Abshire, Tromp and White', 5758, true);
insert into goods (id, name, description, price, in_stock) values (31, 'Arleen', 'O''Reilly-Monahan', 93916, false);
insert into goods (id, name, description, price, in_stock) values (32, 'Chelsie', 'Emmerich, Johns and Yundt', 7222, false);
insert into goods (id, name, description, price, in_stock) values (33, 'Manda', 'Nitzsche, Predovic and Kulas', 59735, false);
insert into goods (id, name, description, price, in_stock) values (34, 'Nessy', 'Larson-Bednar', 5911, false);
insert into goods (id, name, description, price, in_stock) values (35, 'Joscelin', 'Cruickshank LLC', 3771, false);
insert into goods (id, name, description, price, in_stock) values (36, 'Lorita', 'Spencer and Sons', 64423, true);
insert into goods (id, name, description, price, in_stock) values (37, 'Carena', 'Klocko-Smitham', 76671, true);
insert into goods (id, name, description, price, in_stock) values (38, 'Arlette', 'Murray-Cronin', 10850, false);
insert into goods (id, name, description, price, in_stock) values (39, 'Adora', 'Wintheiser, Jacobson and Kunze', 29987, true);
insert into goods (id, name, description, price, in_stock) values (40, 'Shanta', 'Mills, Kirlin and Thiel', 92131, false);
insert into goods (id, name, description, price, in_stock) values (41, 'Jorie', 'Wolff-Daugherty', 41888, true);
insert into goods (id, name, description, price, in_stock) values (42, 'Meridel', 'Hermiston, Klocko and Carter', 86121, false);
insert into goods (id, name, description, price, in_stock) values (43, 'Lolly', 'Hodkiewicz, Will and Mosciski', 79535, true);
insert into goods (id, name, description, price, in_stock) values (44, 'Dee', 'Mertz, Beatty and Klein', 66941, false);
insert into goods (id, name, description, price, in_stock) values (45, 'Rosalinda', 'Hand, Ondricka and Auer', 51464, true);
insert into goods (id, name, description, price, in_stock) values (46, 'Rebekkah', 'Bode LLC', 30829, true);
insert into goods (id, name, description, price, in_stock) values (47, 'Brittne', 'Medhurst and Sons', 72560, false);
insert into goods (id, name, description, price, in_stock) values (48, 'Dorisa', 'Kuphal and Sons', 59180, true);
insert into goods (id, name, description, price, in_stock) values (49, 'Isabelle', 'Tillman-Hayes', 18751, true);
insert into goods (id, name, description, price, in_stock) values (50, 'Joanne', 'Mills, Parker and Osinski', 61232, false);
insert into goods (id, name, description, price, in_stock) values (51, 'Amelita', 'Blanda, Rosenbaum and Monahan', 42995, true);
insert into goods (id, name, description, price, in_stock) values (52, 'Alverta', 'Hackett Inc', 83225, true);
insert into goods (id, name, description, price, in_stock) values (53, 'Electra', 'Runte and Sons', 47028, false);
insert into goods (id, name, description, price, in_stock) values (54, 'Ardelle', 'Flatley LLC', 21683, false);
insert into goods (id, name, description, price, in_stock) values (55, 'Sybyl', 'Abernathy-O''Kon', 48956, false);
insert into goods (id, name, description, price, in_stock) values (56, 'Dorelle', 'Champlin and Sons', 43484, true);
insert into goods (id, name, description, price, in_stock) values (57, 'Paige', 'Osinski LLC', 7865, true);
insert into goods (id, name, description, price, in_stock) values (58, 'Adrienne', 'Connelly, Krajcik and Collins', 76939, false);
insert into goods (id, name, description, price, in_stock) values (59, 'Helen-elizabeth', 'Braun Group', 88532, false);
insert into goods (id, name, description, price, in_stock) values (60, 'Gabriellia', 'Rowe, Raynor and Kuhlman', 76674, true);
insert into goods (id, name, description, price, in_stock) values (61, 'Auroora', 'Grady and Sons', 96962, false);
insert into goods (id, name, description, price, in_stock) values (62, 'Cari', 'Goodwin, Gorczany and Ernser', 36843, false);
insert into goods (id, name, description, price, in_stock) values (63, 'Jaimie', 'Beier LLC', 55623, true);
insert into goods (id, name, description, price, in_stock) values (64, 'Rosina', 'Schroeder-Murphy', 79636, false);
insert into goods (id, name, description, price, in_stock) values (65, 'Jannel', 'Jacobs and Sons', 65344, true);
insert into goods (id, name, description, price, in_stock) values (66, 'Stacy', 'Wolff and Sons', 71916, true);
insert into goods (id, name, description, price, in_stock) values (67, 'Martica', 'Metz-Swift', 70118, false);
insert into goods (id, name, description, price, in_stock) values (68, 'Joell', 'Pollich, Hilpert and Grant', 23345, true);
insert into goods (id, name, description, price, in_stock) values (69, 'Dania', 'Torphy Inc', 43786, false);
insert into goods (id, name, description, price, in_stock) values (70, 'Winnah', 'Schmitt, Mann and Bartoletti', 86206, false);
insert into goods (id, name, description, price, in_stock) values (71, 'Ferdinande', 'Baumbach, Lang and Hermiston', 61597, false);
insert into goods (id, name, description, price, in_stock) values (72, 'Almeria', 'Keeling and Sons', 38626, true);
insert into goods (id, name, description, price, in_stock) values (73, 'Layne', 'Hayes, Fritsch and Okuneva', 8043, false);
insert into goods (id, name, description, price, in_stock) values (74, 'Catriona', 'Corkery Group', 4862, false);
insert into goods (id, name, description, price, in_stock) values (75, 'Yvette', 'Luettgen-Harber', 82055, true);
insert into goods (id, name, description, price, in_stock) values (76, 'Alikee', 'Fay LLC', 13399, true);
insert into goods (id, name, description, price, in_stock) values (77, 'Madalena', 'Ortiz and Sons', 17927, false);
insert into goods (id, name, description, price, in_stock) values (78, 'Dani', 'Koss-Dibbert', 48750, false);
insert into goods (id, name, description, price, in_stock) values (79, 'Kaela', 'Thompson Group', 13874, false);
insert into goods (id, name, description, price, in_stock) values (80, 'Pat', 'Morar Inc', 64136, false);
insert into goods (id, name, description, price, in_stock) values (81, 'Haleigh', 'Weber Inc', 83478, true);
insert into goods (id, name, description, price, in_stock) values (82, 'Arabelle', 'Mills, Kemmer and Corwin', 73408, true);
insert into goods (id, name, description, price, in_stock) values (83, 'Sarina', 'Yundt-Reynolds', 31206, false);
insert into goods (id, name, description, price, in_stock) values (84, 'Shanda', 'Kuvalis-Reynolds', 14352, false);
insert into goods (id, name, description, price, in_stock) values (85, 'Brit', 'Stamm and Sons', 64267, true);
insert into goods (id, name, description, price, in_stock) values (86, 'Bernadette', 'Moore, Schuppe and Howe', 27859, false);
insert into goods (id, name, description, price, in_stock) values (87, 'Aurie', 'Turner-Crooks', 38395, true);
insert into goods (id, name, description, price, in_stock) values (88, 'Ardenia', 'Ebert, Lakin and Romaguera', 27487, false);
insert into goods (id, name, description, price, in_stock) values (89, 'Drucie', 'Jast-Olson', 58517, true);
insert into goods (id, name, description, price, in_stock) values (90, 'Kendre', 'Haag LLC', 13134, true);
insert into goods (id, name, description, price, in_stock) values (91, 'Fernanda', 'Kuhn, Kunze and Schimmel', 61288, true);
insert into goods (id, name, description, price, in_stock) values (92, 'Minerva', 'Cummerata, Daniel and Rowe', 84377, false);
insert into goods (id, name, description, price, in_stock) values (93, 'Arleyne', 'Metz, Zboncak and Emmerich', 46008, false);
insert into goods (id, name, description, price, in_stock) values (94, 'Allison', 'Renner-Hayes', 13115, true);
insert into goods (id, name, description, price, in_stock) values (95, 'Dode', 'Green and Sons', 5969, true);
insert into goods (id, name, description, price, in_stock) values (96, 'Caro', 'Donnelly-Murray', 28858, true);
insert into goods (id, name, description, price, in_stock) values (97, 'Klara', 'Hilpert-Johnston', 81851, false);
insert into goods (id, name, description, price, in_stock) values (98, 'Hailee', 'Cronin-Smith', 86138, false);
insert into goods (id, name, description, price, in_stock) values (99, 'Libbie', 'Koelpin, Mohr and Kub', 17256, true);
insert into goods (id, name, description, price, in_stock) values (100, 'Binni', 'Hermann and Sons', 8198, false);
insert into goods (id, name, description, price, in_stock) values (101, 'Nickie', 'Gottlieb-Nolan', 46887, false);
insert into goods (id, name, description, price, in_stock) values (102, 'Rozina', 'Osinski, Bayer and Bartell', 17080, true);
insert into goods (id, name, description, price, in_stock) values (103, 'Talyah', 'Goodwin, Kiehn and Dach', 86477, true);
insert into goods (id, name, description, price, in_stock) values (104, 'Yovonnda', 'D''Amore LLC', 33076, false);
insert into goods (id, name, description, price, in_stock) values (105, 'Astra', 'Harber-Gislason', 51875, false);
insert into goods (id, name, description, price, in_stock) values (106, 'Darrelle', 'Paucek-Harvey', 33418, false);
insert into goods (id, name, description, price, in_stock) values (107, 'Rosanne', 'Von, Rippin and Hagenes', 89546, true);
insert into goods (id, name, description, price, in_stock) values (108, 'Leodora', 'O''Reilly-Cassin', 71732, true);
insert into goods (id, name, description, price, in_stock) values (109, 'Emili', 'Monahan Group', 22293, false);
insert into goods (id, name, description, price, in_stock) values (110, 'Beverlie', 'Cartwright-Smitham', 19457, false);
insert into goods (id, name, description, price, in_stock) values (111, 'Lauretta', 'Huel and Sons', 62984, true);
insert into goods (id, name, description, price, in_stock) values (112, 'Bernetta', 'Vandervort-Roberts', 32185, false);
insert into goods (id, name, description, price, in_stock) values (113, 'Opaline', 'Leuschke and Sons', 57195, false);
insert into goods (id, name, description, price, in_stock) values (114, 'Inger', 'O''Conner-Kuphal', 28346, false);
insert into goods (id, name, description, price, in_stock) values (115, 'Mavis', 'Willms Inc', 53769, true);
insert into goods (id, name, description, price, in_stock) values (116, 'Camilla', 'Blick, Renner and Ondricka', 23348, false);
insert into goods (id, name, description, price, in_stock) values (117, 'Hynda', 'Reichert-Jaskolski', 44469, true);
insert into goods (id, name, description, price, in_stock) values (118, 'Willy', 'Hirthe Inc', 19667, true);
insert into goods (id, name, description, price, in_stock) values (119, 'Lilian', 'Berge, Rempel and Williamson', 18291, true);
insert into goods (id, name, description, price, in_stock) values (120, 'Hanna', 'Bode-Beer', 99660, true);
insert into goods (id, name, description, price, in_stock) values (121, 'Kerstin', 'Dickens Group', 32023, true);
insert into goods (id, name, description, price, in_stock) values (122, 'Adoree', 'Mayert-Friesen', 97836, false);
insert into goods (id, name, description, price, in_stock) values (123, 'Damaris', 'Beier-Franecki', 32841, true);
insert into goods (id, name, description, price, in_stock) values (124, 'Patricia', 'Bahringer-Green', 73911, false);
insert into goods (id, name, description, price, in_stock) values (125, 'Allene', 'Murazik Group', 64744, true);
insert into goods (id, name, description, price, in_stock) values (126, 'Barbara-anne', 'Borer-Lehner', 88982, false);
insert into goods (id, name, description, price, in_stock) values (127, 'Beverley', 'Mills Group', 81214, false);
insert into goods (id, name, description, price, in_stock) values (128, 'Masha', 'Witting, Hoppe and Satterfield', 86636, true);
insert into goods (id, name, description, price, in_stock) values (129, 'Cassandry', 'Jast, Kihn and Klocko', 96147, false);
insert into goods (id, name, description, price, in_stock) values (130, 'Marybeth', 'Tremblay-Fadel', 74087, true);
insert into goods (id, name, description, price, in_stock) values (131, 'Elicia', 'Wyman, Fisher and Volkman', 89556, true);
insert into goods (id, name, description, price, in_stock) values (132, 'Clareta', 'Blanda-Welch', 54437, false);
insert into goods (id, name, description, price, in_stock) values (133, 'Rivy', 'Blick, Skiles and Marquardt', 20106, true);
insert into goods (id, name, description, price, in_stock) values (134, 'Chelsy', 'Willms and Sons', 25766, false);
insert into goods (id, name, description, price, in_stock) values (135, 'Maye', 'Bernhard-Watsica', 93769, false);
insert into goods (id, name, description, price, in_stock) values (136, 'Caprice', 'Grady, Gutmann and Sipes', 59244, false);
insert into goods (id, name, description, price, in_stock) values (137, 'Rubetta', 'Russel-Renner', 58418, true);
insert into goods (id, name, description, price, in_stock) values (138, 'Roxane', 'Quitzon-Keeling', 65916, true);
insert into goods (id, name, description, price, in_stock) values (139, 'Ranna', 'Herman Inc', 53082, false);
insert into goods (id, name, description, price, in_stock) values (140, 'Gates', 'Bernier, Hagenes and Satterfield', 24636, true);
insert into goods (id, name, description, price, in_stock) values (141, 'Corny', 'Spencer and Sons', 28288, true);
insert into goods (id, name, description, price, in_stock) values (142, 'Gusella', 'Harris-Yost', 68788, false);
insert into goods (id, name, description, price, in_stock) values (143, 'Bernice', 'Cummings-Hettinger', 21216, true);
insert into goods (id, name, description, price, in_stock) values (144, 'Cleopatra', 'Larson Group', 85826, false);
insert into goods (id, name, description, price, in_stock) values (145, 'Nydia', 'Marks Inc', 22248, false);
insert into goods (id, name, description, price, in_stock) values (146, 'Melony', 'Franecki, Hayes and Reinger', 8755, true);
insert into goods (id, name, description, price, in_stock) values (147, 'Aimee', 'Runolfsson LLC', 51233, false);
insert into goods (id, name, description, price, in_stock) values (148, 'Ashleigh', 'Schuster, Miller and Effertz', 12815, false);
insert into goods (id, name, description, price, in_stock) values (149, 'Kittie', 'Turcotte, Rogahn and Lueilwitz', 12376, true);
insert into goods (id, name, description, price, in_stock) values (150, 'Arlen', 'Zieme Inc', 7288, true);
insert into goods (id, name, description, price, in_stock) values (151, 'Mavis', 'Haag, Champlin and Mills', 52701, false);
insert into goods (id, name, description, price, in_stock) values (152, 'Tabatha', 'Boyer-Berge', 94453, true);
insert into goods (id, name, description, price, in_stock) values (153, 'Jill', 'Baumbach-Muller', 74290, true);
insert into goods (id, name, description, price, in_stock) values (154, 'Florance', 'Collier-Erdman', 14602, false);
insert into goods (id, name, description, price, in_stock) values (155, 'Austine', 'Wehner LLC', 66530, false);
insert into goods (id, name, description, price, in_stock) values (156, 'Darleen', 'Boyer-Champlin', 65330, true);
insert into goods (id, name, description, price, in_stock) values (157, 'Julee', 'Boyle Inc', 95559, false);
insert into goods (id, name, description, price, in_stock) values (158, 'Vivienne', 'Morissette, Gislason and Corkery', 12982, true);
insert into goods (id, name, description, price, in_stock) values (159, 'Noella', 'Gorczany, Toy and Cronin', 61410, true);
insert into goods (id, name, description, price, in_stock) values (160, 'Kinna', 'Bashirian-Morissette', 71920, true);
insert into goods (id, name, description, price, in_stock) values (161, 'Sheelah', 'Raynor Group', 42552, false);
insert into goods (id, name, description, price, in_stock) values (162, 'Dulcinea', 'Wintheiser, Lakin and Green', 85109, false);
insert into goods (id, name, description, price, in_stock) values (163, 'Dixie', 'Auer, Bogan and Abshire', 11333, true);
insert into goods (id, name, description, price, in_stock) values (164, 'Gerianne', 'Cole-Dietrich', 7443, false);
insert into goods (id, name, description, price, in_stock) values (165, 'Cass', 'Okuneva, Funk and Bogisich', 50355, true);
insert into goods (id, name, description, price, in_stock) values (166, 'Zita', 'Gleason-Swaniawski', 92050, false);
insert into goods (id, name, description, price, in_stock) values (167, 'Rose', 'Bailey and Sons', 60059, false);
insert into goods (id, name, description, price, in_stock) values (168, 'Tommie', 'Bashirian, Stamm and Bradtke', 26743, false);
insert into goods (id, name, description, price, in_stock) values (169, 'Kelila', 'Veum, Emard and Wisoky', 40970, true);
insert into goods (id, name, description, price, in_stock) values (170, 'Gail', 'Lemke-VonRueden', 48770, false);
insert into goods (id, name, description, price, in_stock) values (171, 'Freida', 'Blick-Sauer', 6524, false);
insert into goods (id, name, description, price, in_stock) values (172, 'Catharina', 'Auer Group', 36259, true);
insert into goods (id, name, description, price, in_stock) values (173, 'Herminia', 'Schiller-Schmidt', 51635, false);
insert into goods (id, name, description, price, in_stock) values (174, 'Adi', 'Hand-Jast', 57567, true);
insert into goods (id, name, description, price, in_stock) values (175, 'Rosalind', 'Sipes LLC', 39286, true);
insert into goods (id, name, description, price, in_stock) values (176, 'Ekaterina', 'Gibson, Rath and Hintz', 62388, false);
insert into goods (id, name, description, price, in_stock) values (177, 'Belita', 'Bergnaum and Sons', 15993, true);
insert into goods (id, name, description, price, in_stock) values (178, 'Sharl', 'Keebler Inc', 65501, true);
insert into goods (id, name, description, price, in_stock) values (179, 'Eleanore', 'Crona, Brekke and Koss', 4911, false);
insert into goods (id, name, description, price, in_stock) values (180, 'Cornie', 'Grimes, Schumm and Brakus', 88997, true);
insert into goods (id, name, description, price, in_stock) values (181, 'Philly', 'Kuhlman-Douglas', 12200, false);
insert into goods (id, name, description, price, in_stock) values (182, 'Orelia', 'Mraz LLC', 27405, false);
insert into goods (id, name, description, price, in_stock) values (183, 'Hettie', 'Roberts-Thompson', 41721, true);
insert into goods (id, name, description, price, in_stock) values (184, 'Jonis', 'Hermiston, DuBuque and Kemmer', 75093, false);
insert into goods (id, name, description, price, in_stock) values (185, 'Nelli', 'Tremblay-Dickens', 46156, false);
insert into goods (id, name, description, price, in_stock) values (186, 'Emelita', 'Armstrong-Nikolaus', 68993, false);
insert into goods (id, name, description, price, in_stock) values (187, 'Fara', 'Schinner-Hettinger', 79267, false);
insert into goods (id, name, description, price, in_stock) values (188, 'Ann-marie', 'Waters Group', 46661, true);
insert into goods (id, name, description, price, in_stock) values (189, 'Joy', 'Haley, Christiansen and Kessler', 41152, true);
insert into goods (id, name, description, price, in_stock) values (190, 'Tonye', 'Swaniawski and Sons', 1980, false);
insert into goods (id, name, description, price, in_stock) values (191, 'Tybi', 'Mayert-Nolan', 85453, false);
insert into goods (id, name, description, price, in_stock) values (192, 'Bethena', 'Gulgowski-Lang', 37682, true);
insert into goods (id, name, description, price, in_stock) values (193, 'Madge', 'Welch-Marquardt', 25755, false);
insert into goods (id, name, description, price, in_stock) values (194, 'Maible', 'Mohr-Jakubowski', 53704, true);
insert into goods (id, name, description, price, in_stock) values (195, 'Janeczka', 'Jenkins and Sons', 70990, true);
insert into goods (id, name, description, price, in_stock) values (196, 'Darleen', 'Torphy, Lakin and Schamberger', 47715, true);
insert into goods (id, name, description, price, in_stock) values (197, 'Dani', 'Jerde-Carroll', 76017, false);
insert into goods (id, name, description, price, in_stock) values (198, 'Lacie', 'Nitzsche, Collier and Cassin', 8740, false);
insert into goods (id, name, description, price, in_stock) values (199, 'Tony', 'Effertz-Robel', 44353, true);
insert into goods (id, name, description, price, in_stock) values (200, 'Harriett', 'Graham-Leuschke', 19698, true);
insert into goods (id, name, description, price, in_stock) values (201, 'Margarette', 'Parisian-Ruecker', 21095, true);
insert into goods (id, name, description, price, in_stock) values (202, 'Lyndell', 'Bergstrom-Waelchi', 77002, true);
insert into goods (id, name, description, price, in_stock) values (203, 'Margarethe', 'Halvorson Group', 94059, false);
insert into goods (id, name, description, price, in_stock) values (204, 'Jourdan', 'Gleason-Mann', 30345, true);
insert into goods (id, name, description, price, in_stock) values (205, 'Kevina', 'Torp LLC', 61786, true);
insert into goods (id, name, description, price, in_stock) values (206, 'Octavia', 'Nolan, Moen and Yost', 43477, true);
insert into goods (id, name, description, price, in_stock) values (207, 'Leanora', 'Konopelski-Bergstrom', 4529, true);
insert into goods (id, name, description, price, in_stock) values (208, 'Renelle', 'Klocko and Sons', 75409, false);
insert into goods (id, name, description, price, in_stock) values (209, 'Robbi', 'Douglas LLC', 78184, false);
insert into goods (id, name, description, price, in_stock) values (210, 'Marcy', 'Kuphal-Gleason', 43790, false);
insert into goods (id, name, description, price, in_stock) values (211, 'Verile', 'Kilback-Rogahn', 38737, false);
insert into goods (id, name, description, price, in_stock) values (212, 'Sonja', 'Barrows Group', 74621, true);
insert into goods (id, name, description, price, in_stock) values (213, 'Marleen', 'Leffler Inc', 10598, false);
insert into goods (id, name, description, price, in_stock) values (214, 'Milzie', 'Boehm, Wintheiser and Homenick', 15052, true);
insert into goods (id, name, description, price, in_stock) values (215, 'Celia', 'Runolfsdottir, Pfannerstill and Fay', 43506, false);
insert into goods (id, name, description, price, in_stock) values (216, 'Michal', 'Wolff Group', 89047, true);
insert into goods (id, name, description, price, in_stock) values (217, 'Sabrina', 'Blick-Lueilwitz', 3029, false);
insert into goods (id, name, description, price, in_stock) values (218, 'Feliza', 'Rutherford-Predovic', 77151, true);
insert into goods (id, name, description, price, in_stock) values (219, 'Lynsey', 'Schimmel-Hamill', 29827, false);
insert into goods (id, name, description, price, in_stock) values (220, 'Daniela', 'Legros, Kris and Ullrich', 54165, true);
insert into goods (id, name, description, price, in_stock) values (221, 'Elana', 'Parker-Kling', 52923, false);
insert into goods (id, name, description, price, in_stock) values (222, 'Brier', 'Christiansen-Gorczany', 61118, true);
insert into goods (id, name, description, price, in_stock) values (223, 'Jeannie', 'Kemmer-Bogisich', 38984, true);
insert into goods (id, name, description, price, in_stock) values (224, 'Misty', 'Stoltenberg-Conn', 27145, true);
insert into goods (id, name, description, price, in_stock) values (225, 'Judith', 'Okuneva and Sons', 16681, false);
insert into goods (id, name, description, price, in_stock) values (226, 'Carmel', 'Feil Group', 33140, true);
insert into goods (id, name, description, price, in_stock) values (227, 'Kendra', 'Rohan, O''Kon and Herzog', 17567, true);
insert into goods (id, name, description, price, in_stock) values (228, 'Valera', 'Towne-Willms', 26325, false);
insert into goods (id, name, description, price, in_stock) values (229, 'Basia', 'Murphy and Sons', 60064, true);
insert into goods (id, name, description, price, in_stock) values (230, 'Rosella', 'O''Conner Group', 6149, false);
insert into goods (id, name, description, price, in_stock) values (231, 'Agneta', 'Zieme and Sons', 57362, true);
insert into goods (id, name, description, price, in_stock) values (232, 'Bee', 'Wintheiser, King and Pollich', 52828, false);
insert into goods (id, name, description, price, in_stock) values (233, 'Charmaine', 'Nienow-Larson', 86950, false);
insert into goods (id, name, description, price, in_stock) values (234, 'Stormy', 'Goldner-Breitenberg', 75159, true);
insert into goods (id, name, description, price, in_stock) values (235, 'Orsola', 'Lynch-Pagac', 43447, false);
insert into goods (id, name, description, price, in_stock) values (236, 'Lelia', 'Rippin, Satterfield and Schiller', 4287, true);
insert into goods (id, name, description, price, in_stock) values (237, 'Leanna', 'Wintheiser LLC', 46377, false);
insert into goods (id, name, description, price, in_stock) values (238, 'Bekki', 'Hermiston Inc', 73522, true);
insert into goods (id, name, description, price, in_stock) values (239, 'Margareta', 'Shields LLC', 54542, false);
insert into goods (id, name, description, price, in_stock) values (240, 'Sophia', 'Swift, Carroll and Mitchell', 56437, true);
insert into goods (id, name, description, price, in_stock) values (241, 'Tiffani', 'Mohr Group', 46389, true);
insert into goods (id, name, description, price, in_stock) values (242, 'Georgeta', 'Donnelly-Herman', 7677, true);
insert into goods (id, name, description, price, in_stock) values (243, 'Gunilla', 'Sanford-Hills', 36289, true);
insert into goods (id, name, description, price, in_stock) values (244, 'Karlene', 'Vandervort, Buckridge and Champlin', 77386, true);
insert into goods (id, name, description, price, in_stock) values (245, 'Carilyn', 'Medhurst, Funk and Kerluke', 33118, false);
insert into goods (id, name, description, price, in_stock) values (246, 'Dacie', 'Gleichner-Altenwerth', 26699, false);
insert into goods (id, name, description, price, in_stock) values (247, 'Desiree', 'Maggio LLC', 53501, true);
insert into goods (id, name, description, price, in_stock) values (248, 'Lissie', 'Schmeler Inc', 62446, false);
insert into goods (id, name, description, price, in_stock) values (249, 'Darsey', 'West-Block', 24402, false);
insert into goods (id, name, description, price, in_stock) values (250, 'Elizabet', 'Hackett-Hyatt', 4845, false);
insert into goods (id, name, description, price, in_stock) values (251, 'Brear', 'Rutherford, Runolfsson and Quigley', 83027, true);
insert into goods (id, name, description, price, in_stock) values (252, 'Madel', 'Jast and Sons', 68503, true);
insert into goods (id, name, description, price, in_stock) values (253, 'Laryssa', 'Balistreri Inc', 97309, true);
insert into goods (id, name, description, price, in_stock) values (254, 'Darla', 'Koss, Towne and Labadie', 22965, false);
insert into goods (id, name, description, price, in_stock) values (255, 'Nicoline', 'Maggio and Sons', 76218, true);
insert into goods (id, name, description, price, in_stock) values (256, 'Petronilla', 'Baumbach-Koch', 1852, false);
insert into goods (id, name, description, price, in_stock) values (257, 'Anita', 'Kautzer-Oberbrunner', 23903, true);
insert into goods (id, name, description, price, in_stock) values (258, 'Else', 'Labadie, Leannon and Gulgowski', 6256, true);
insert into goods (id, name, description, price, in_stock) values (259, 'Casi', 'Satterfield, MacGyver and Moore', 88308, false);
insert into goods (id, name, description, price, in_stock) values (260, 'Elna', 'Bogan and Sons', 66103, true);
insert into goods (id, name, description, price, in_stock) values (261, 'Vanya', 'Bergnaum Group', 33635, true);
insert into goods (id, name, description, price, in_stock) values (262, 'Andriette', 'Ebert Group', 67858, false);
insert into goods (id, name, description, price, in_stock) values (263, 'Audrey', 'Walker and Sons', 74014, false);
insert into goods (id, name, description, price, in_stock) values (264, 'Anastassia', 'Hermann-Hartmann', 4032, false);
insert into goods (id, name, description, price, in_stock) values (265, 'Joyan', 'Miller and Sons', 21602, true);
insert into goods (id, name, description, price, in_stock) values (266, 'Salomi', 'Ruecker and Sons', 10150, true);
insert into goods (id, name, description, price, in_stock) values (267, 'Maridel', 'Kunde-Schmeler', 67366, true);
insert into goods (id, name, description, price, in_stock) values (268, 'Sheba', 'Willms Group', 49941, true);
insert into goods (id, name, description, price, in_stock) values (269, 'Ursuline', 'Auer, Abshire and Torphy', 77139, false);
insert into goods (id, name, description, price, in_stock) values (270, 'Margareta', 'Feil LLC', 55493, true);
insert into goods (id, name, description, price, in_stock) values (271, 'Katey', 'Graham-Walter', 74972, false);
insert into goods (id, name, description, price, in_stock) values (272, 'Risa', 'Brekke LLC', 89644, true);
insert into goods (id, name, description, price, in_stock) values (273, 'Merrill', 'Mitchell LLC', 47883, true);
insert into goods (id, name, description, price, in_stock) values (274, 'Aloise', 'Boyle, Hayes and Casper', 34351, false);
insert into goods (id, name, description, price, in_stock) values (275, 'Bethany', 'Satterfield, Heller and Roob', 33252, true);
insert into goods (id, name, description, price, in_stock) values (276, 'Cecilla', 'Swift Group', 39034, false);
insert into goods (id, name, description, price, in_stock) values (277, 'Patti', 'Bergstrom, Feeney and Legros', 67852, true);
insert into goods (id, name, description, price, in_stock) values (278, 'Carroll', 'Hermiston-Leuschke', 85876, true);
insert into goods (id, name, description, price, in_stock) values (279, 'Peggie', 'Schiller Inc', 31687, false);
insert into goods (id, name, description, price, in_stock) values (280, 'Glenn', 'Bernhard-Waelchi', 94263, true);
insert into goods (id, name, description, price, in_stock) values (281, 'Lark', 'Kerluke-Stokes', 63966, true);
insert into goods (id, name, description, price, in_stock) values (282, 'Jo-ann', 'Balistreri, Hoppe and Rohan', 40565, false);
insert into goods (id, name, description, price, in_stock) values (283, 'Shandy', 'Batz and Sons', 76764, true);
insert into goods (id, name, description, price, in_stock) values (284, 'Rhetta', 'Hahn-Stracke', 59882, false);
insert into goods (id, name, description, price, in_stock) values (285, 'Olva', 'Barton Inc', 78244, true);
insert into goods (id, name, description, price, in_stock) values (286, 'Annabelle', 'Adams Inc', 65685, false);
insert into goods (id, name, description, price, in_stock) values (287, 'Francyne', 'Bergstrom and Sons', 78350, false);
insert into goods (id, name, description, price, in_stock) values (288, 'Dion', 'Waters LLC', 25115, false);
insert into goods (id, name, description, price, in_stock) values (289, 'Vallie', 'Larson, Morar and Altenwerth', 23447, false);
insert into goods (id, name, description, price, in_stock) values (290, 'Lulu', 'Connelly and Sons', 40362, false);
insert into goods (id, name, description, price, in_stock) values (291, 'Rubi', 'Cartwright, Stoltenberg and Watsica', 89063, false);
insert into goods (id, name, description, price, in_stock) values (292, 'Katya', 'Rowe-Weimann', 85263, true);
insert into goods (id, name, description, price, in_stock) values (293, 'Noel', 'Smitham and Sons', 10313, true);
insert into goods (id, name, description, price, in_stock) values (294, 'Blondell', 'Murazik Inc', 59634, false);
insert into goods (id, name, description, price, in_stock) values (295, 'Rochelle', 'Ankunding LLC', 62571, false);
insert into goods (id, name, description, price, in_stock) values (296, 'Maggy', 'Spinka LLC', 16032, false);
insert into goods (id, name, description, price, in_stock) values (297, 'Oralle', 'Morar Group', 55533, true);
insert into goods (id, name, description, price, in_stock) values (298, 'Lorena', 'Hessel, Raynor and Koch', 33963, true);
insert into goods (id, name, description, price, in_stock) values (299, 'Lenee', 'Kozey, Reichel and Roob', 52168, false);
insert into goods (id, name, description, price, in_stock) values (300, 'Nedi', 'Tremblay-Kunde', 34793, false);
insert into goods (id, name, description, price, in_stock) values (301, 'Nalani', 'Bogan-Stiedemann', 2943, false);
insert into goods (id, name, description, price, in_stock) values (302, 'Ofella', 'Lehner-Watsica', 3168, true);
insert into goods (id, name, description, price, in_stock) values (303, 'Gratia', 'Wyman-Fadel', 36423, false);
insert into goods (id, name, description, price, in_stock) values (304, 'Elyn', 'Wuckert-Bogan', 99175, false);
insert into goods (id, name, description, price, in_stock) values (305, 'Yelena', 'King-Lesch', 37155, true);
insert into goods (id, name, description, price, in_stock) values (306, 'Alidia', 'Zemlak, Hermann and Greenholt', 28033, true);
insert into goods (id, name, description, price, in_stock) values (307, 'Brittany', 'Cummings and Sons', 80086, false);
insert into goods (id, name, description, price, in_stock) values (308, 'Harrie', 'Boyer Group', 84341, true);
insert into goods (id, name, description, price, in_stock) values (309, 'Persis', 'Becker LLC', 36099, true);
insert into goods (id, name, description, price, in_stock) values (310, 'Eryn', 'Koelpin LLC', 46680, false);
insert into goods (id, name, description, price, in_stock) values (311, 'Toma', 'Bartoletti, Dicki and Wolf', 25640, false);
insert into goods (id, name, description, price, in_stock) values (312, 'Tawsha', 'Krajcik Inc', 11556, false);
insert into goods (id, name, description, price, in_stock) values (313, 'Nanny', 'Gleichner, Jenkins and Dare', 32279, false);
insert into goods (id, name, description, price, in_stock) values (314, 'Yasmeen', 'Parker, Greenfelder and Carter', 2074, false);
insert into goods (id, name, description, price, in_stock) values (315, 'Galina', 'Block, Corwin and Erdman', 14785, false);
insert into goods (id, name, description, price, in_stock) values (316, 'Edna', 'Christiansen Group', 4379, true);
insert into goods (id, name, description, price, in_stock) values (317, 'Shelly', 'Predovic and Sons', 73851, true);
insert into goods (id, name, description, price, in_stock) values (318, 'Ana', 'Ondricka, Pfeffer and O''Conner', 81414, false);
insert into goods (id, name, description, price, in_stock) values (319, 'Ange', 'Zulauf LLC', 33518, true);
insert into goods (id, name, description, price, in_stock) values (320, 'Merrile', 'Stoltenberg, Ernser and Bauch', 77227, true);
insert into goods (id, name, description, price, in_stock) values (321, 'Bianka', 'Keeling-Carroll', 19489, false);
insert into goods (id, name, description, price, in_stock) values (322, 'Irita', 'Hamill, Bernier and Schumm', 2341, true);
insert into goods (id, name, description, price, in_stock) values (323, 'Roxane', 'Satterfield LLC', 18654, true);
insert into goods (id, name, description, price, in_stock) values (324, 'Margie', 'Gerlach-Lueilwitz', 11415, false);
insert into goods (id, name, description, price, in_stock) values (325, 'Tabbi', 'Anderson Inc', 51710, false);
insert into goods (id, name, description, price, in_stock) values (326, 'Rosella', 'Smitham LLC', 48210, false);
insert into goods (id, name, description, price, in_stock) values (327, 'Wendye', 'Bergstrom, Johnson and Waelchi', 10463, false);
insert into goods (id, name, description, price, in_stock) values (328, 'Pamelina', 'Hayes-Watsica', 52437, true);
insert into goods (id, name, description, price, in_stock) values (329, 'Annmarie', 'Ankunding, Dicki and Yost', 99514, true);
insert into goods (id, name, description, price, in_stock) values (330, 'Yelena', 'Stark, Stokes and Dach', 80906, true);
insert into goods (id, name, description, price, in_stock) values (331, 'Dinny', 'Abbott, Brown and Powlowski', 63505, true);
insert into goods (id, name, description, price, in_stock) values (332, 'Paige', 'Hodkiewicz-Boyle', 66418, true);
insert into goods (id, name, description, price, in_stock) values (333, 'Rozele', 'Klocko, Farrell and Nolan', 17260, false);
insert into goods (id, name, description, price, in_stock) values (334, 'Manda', 'Grant, Oberbrunner and Hirthe', 13465, false);
insert into goods (id, name, description, price, in_stock) values (335, 'Devinne', 'Murray and Sons', 57025, false);
insert into goods (id, name, description, price, in_stock) values (336, 'Sabra', 'Daniel, West and Mayert', 21499, false);
insert into goods (id, name, description, price, in_stock) values (337, 'Bobina', 'Brekke and Sons', 89118, false);
insert into goods (id, name, description, price, in_stock) values (338, 'Jeana', 'Kiehn, Williamson and Larson', 62753, false);
insert into goods (id, name, description, price, in_stock) values (339, 'Clari', 'Jacobson-Hirthe', 93971, false);
insert into goods (id, name, description, price, in_stock) values (340, 'Margot', 'Hand-Braun', 39964, false);
insert into goods (id, name, description, price, in_stock) values (341, 'Lynnelle', 'Effertz-Dach', 87653, false);
insert into goods (id, name, description, price, in_stock) values (342, 'Dora', 'Turcotte, Terry and Christiansen', 99097, false);
insert into goods (id, name, description, price, in_stock) values (343, 'Lorelle', 'Jaskolski, Sanford and Sawayn', 17236, false);
insert into goods (id, name, description, price, in_stock) values (344, 'Cyndia', 'Walker-Lockman', 71077, true);
insert into goods (id, name, description, price, in_stock) values (345, 'Tabbatha', 'O''Connell-Marvin', 56275, true);
insert into goods (id, name, description, price, in_stock) values (346, 'Jobye', 'Carter-Lindgren', 22710, true);
insert into goods (id, name, description, price, in_stock) values (347, 'Ulrike', 'Bailey, Jast and Cronin', 63688, false);
insert into goods (id, name, description, price, in_stock) values (348, 'Alyce', 'Streich, Cummings and Hegmann', 17751, false);
insert into goods (id, name, description, price, in_stock) values (349, 'Darlleen', 'Beatty-Von', 43776, false);
insert into goods (id, name, description, price, in_stock) values (350, 'Milka', 'Ratke, Muller and DuBuque', 69538, false);
insert into goods (id, name, description, price, in_stock) values (351, 'Shirleen', 'Ondricka Group', 69834, true);
insert into goods (id, name, description, price, in_stock) values (352, 'Jenica', 'Welch, Tromp and Wehner', 28520, true);
insert into goods (id, name, description, price, in_stock) values (353, 'Carolynn', 'Metz, Boyer and Hermann', 15785, false);
insert into goods (id, name, description, price, in_stock) values (354, 'Shea', 'Adams-Lueilwitz', 49987, true);
insert into goods (id, name, description, price, in_stock) values (355, 'Pegeen', 'Batz-McLaughlin', 51159, true);
insert into goods (id, name, description, price, in_stock) values (356, 'Annadiana', 'Homenick-Greenholt', 90263, false);
insert into goods (id, name, description, price, in_stock) values (357, 'Danna', 'Thompson-Kuvalis', 80012, true);
insert into goods (id, name, description, price, in_stock) values (358, 'Zorina', 'Hegmann, Bergnaum and Turcotte', 89049, true);
insert into goods (id, name, description, price, in_stock) values (359, 'Beitris', 'Gerlach-Sawayn', 22288, true);
insert into goods (id, name, description, price, in_stock) values (360, 'Lory', 'West-McDermott', 44424, false);
insert into goods (id, name, description, price, in_stock) values (361, 'Elle', 'Simonis LLC', 2790, false);
insert into goods (id, name, description, price, in_stock) values (362, 'Josefina', 'Koepp-Crona', 76456, true);
insert into goods (id, name, description, price, in_stock) values (363, 'Amandy', 'Friesen and Sons', 1296, false);
insert into goods (id, name, description, price, in_stock) values (364, 'Ninetta', 'Cummings-Hermann', 65053, false);
insert into goods (id, name, description, price, in_stock) values (365, 'Dorie', 'McDermott, Kertzmann and Mills', 32460, true);
insert into goods (id, name, description, price, in_stock) values (366, 'Sharron', 'Ullrich Inc', 80706, true);
insert into goods (id, name, description, price, in_stock) values (367, 'Neda', 'Marks-Connelly', 34681, true);
insert into goods (id, name, description, price, in_stock) values (368, 'Lucila', 'Runolfsson and Sons', 86289, true);
insert into goods (id, name, description, price, in_stock) values (369, 'Gnni', 'Friesen, Kassulke and Altenwerth', 57115, false);
insert into goods (id, name, description, price, in_stock) values (370, 'Ginny', 'Bednar, Schmitt and Labadie', 82803, false);
insert into goods (id, name, description, price, in_stock) values (371, 'Amelia', 'Windler Inc', 58354, false);
insert into goods (id, name, description, price, in_stock) values (372, 'Carlin', 'Borer Inc', 11885, true);
insert into goods (id, name, description, price, in_stock) values (373, 'Annadiana', 'Kshlerin-Ledner', 30589, true);
insert into goods (id, name, description, price, in_stock) values (374, 'Ruthie', 'Bins, Kuhlman and Carroll', 50851, true);
insert into goods (id, name, description, price, in_stock) values (375, 'Miguela', 'Cremin-Howell', 36042, true);
insert into goods (id, name, description, price, in_stock) values (376, 'Mariam', 'O''Connell-McCullough', 93281, false);
insert into goods (id, name, description, price, in_stock) values (377, 'Lanna', 'Bashirian-VonRueden', 88549, true);
insert into goods (id, name, description, price, in_stock) values (378, 'Laurice', 'Metz-Wiegand', 29983, false);
insert into goods (id, name, description, price, in_stock) values (379, 'Evaleen', 'Hickle LLC', 210, true);
insert into goods (id, name, description, price, in_stock) values (380, 'Ilka', 'Tromp Inc', 9101, true);
insert into goods (id, name, description, price, in_stock) values (381, 'Blondie', 'Brown, Spinka and Jacobi', 88775, false);
insert into goods (id, name, description, price, in_stock) values (382, 'Susanna', 'Dickinson Inc', 17707, true);
insert into goods (id, name, description, price, in_stock) values (383, 'Vanni', 'Heller and Sons', 5692, false);
insert into goods (id, name, description, price, in_stock) values (384, 'Cordelia', 'Beier-Bogisich', 8249, false);
insert into goods (id, name, description, price, in_stock) values (385, 'Fleur', 'Marvin, Veum and Kreiger', 95792, false);
insert into goods (id, name, description, price, in_stock) values (386, 'Galina', 'Robel Inc', 10925, true);
insert into goods (id, name, description, price, in_stock) values (387, 'Lilas', 'Zieme, Kovacek and Strosin', 11194, false);
insert into goods (id, name, description, price, in_stock) values (388, 'Lanni', 'Emmerich, Watsica and Aufderhar', 54016, true);
insert into goods (id, name, description, price, in_stock) values (389, 'Isabel', 'Cole Group', 53231, false);
insert into goods (id, name, description, price, in_stock) values (390, 'Anett', 'Ledner Inc', 39739, true);
insert into goods (id, name, description, price, in_stock) values (391, 'Valentina', 'Walker-Mohr', 82775, true);
insert into goods (id, name, description, price, in_stock) values (392, 'Hedvige', 'Cassin-Schulist', 18927, false);
insert into goods (id, name, description, price, in_stock) values (393, 'Cate', 'Larson, Stiedemann and Kerluke', 72397, false);
insert into goods (id, name, description, price, in_stock) values (394, 'Susy', 'Bahringer Group', 79122, true);
insert into goods (id, name, description, price, in_stock) values (395, 'Becca', 'Wiza, Waters and White', 99122, true);
insert into goods (id, name, description, price, in_stock) values (396, 'Dyna', 'Wyman-MacGyver', 4488, true);
insert into goods (id, name, description, price, in_stock) values (397, 'Mallorie', 'Kihn-Windler', 5021, false);
insert into goods (id, name, description, price, in_stock) values (398, 'Merralee', 'Koss Inc', 72942, false);
insert into goods (id, name, description, price, in_stock) values (399, 'Alena', 'Mills Inc', 76980, false);
insert into goods (id, name, description, price, in_stock) values (400, 'Flss', 'Nolan and Sons', 97935, true);
insert into goods (id, name, description, price, in_stock) values (401, 'Maiga', 'Rosenbaum, Price and Hoppe', 59062, false);
insert into goods (id, name, description, price, in_stock) values (402, 'Bethina', 'Lebsack LLC', 91099, false);
insert into goods (id, name, description, price, in_stock) values (403, 'Faunie', 'Rodriguez, Boehm and Marquardt', 99583, true);
insert into goods (id, name, description, price, in_stock) values (404, 'Brande', 'Hand, Gusikowski and Cummings', 90114, true);
insert into goods (id, name, description, price, in_stock) values (405, 'Lane', 'Oberbrunner, Schuster and Kris', 96872, false);
insert into goods (id, name, description, price, in_stock) values (406, 'Othilie', 'Legros Group', 80826, true);
insert into goods (id, name, description, price, in_stock) values (407, 'Floria', 'Heidenreich-Walker', 29900, true);
insert into goods (id, name, description, price, in_stock) values (408, 'Blakelee', 'Doyle, Simonis and Anderson', 18841, true);
insert into goods (id, name, description, price, in_stock) values (409, 'Bernardine', 'Quitzon, Price and Bode', 39888, false);
insert into goods (id, name, description, price, in_stock) values (410, 'Zondra', 'Bashirian-Deckow', 19025, true);
insert into goods (id, name, description, price, in_stock) values (411, 'Noelle', 'Wolff, Bednar and Labadie', 53965, false);
insert into goods (id, name, description, price, in_stock) values (412, 'Karola', 'Schowalter, Johnson and Quigley', 96672, true);
insert into goods (id, name, description, price, in_stock) values (413, 'Ruthie', 'Medhurst, Barton and Abernathy', 76041, false);
insert into goods (id, name, description, price, in_stock) values (414, 'Mavra', 'Will and Sons', 56261, false);
insert into goods (id, name, description, price, in_stock) values (415, 'Bobbye', 'Jacobs-Lang', 67059, false);
insert into goods (id, name, description, price, in_stock) values (416, 'Dulciana', 'Schowalter-Welch', 69834, true);
insert into goods (id, name, description, price, in_stock) values (417, 'Rozanna', 'Hauck, Johnston and Deckow', 62210, false);
insert into goods (id, name, description, price, in_stock) values (418, 'Jojo', 'Jast, Donnelly and Jacobi', 81521, false);
insert into goods (id, name, description, price, in_stock) values (419, 'Sibyl', 'Walter-Dietrich', 84103, true);
insert into goods (id, name, description, price, in_stock) values (420, 'Nannette', 'Fisher, Buckridge and Schumm', 98090, false);
insert into goods (id, name, description, price, in_stock) values (421, 'Sheila-kathryn', 'Schmidt, Dietrich and Pagac', 69781, true);
insert into goods (id, name, description, price, in_stock) values (422, 'Alina', 'Senger, Barrows and Satterfield', 80726, false);
insert into goods (id, name, description, price, in_stock) values (423, 'Barb', 'Johns and Sons', 21575, true);
insert into goods (id, name, description, price, in_stock) values (424, 'Clarette', 'Stroman-Johnston', 23838, false);
insert into goods (id, name, description, price, in_stock) values (425, 'Caren', 'Kulas, Stokes and Walsh', 68423, false);
insert into goods (id, name, description, price, in_stock) values (426, 'Jacintha', 'Cummings and Sons', 60552, false);
insert into goods (id, name, description, price, in_stock) values (427, 'Cordula', 'Turner-Kuhn', 72917, true);
insert into goods (id, name, description, price, in_stock) values (428, 'Tawnya', 'Haag-McCullough', 37093, false);
insert into goods (id, name, description, price, in_stock) values (429, 'Tatiania', 'Bode, Baumbach and Watsica', 79016, false);
insert into goods (id, name, description, price, in_stock) values (430, 'Jeniffer', 'Zboncak LLC', 25085, false);
insert into goods (id, name, description, price, in_stock) values (431, 'Sarajane', 'Klein-Mann', 51034, false);
insert into goods (id, name, description, price, in_stock) values (432, 'Vitoria', 'Kunde-Walker', 97947, true);
insert into goods (id, name, description, price, in_stock) values (433, 'Anatola', 'Abernathy, Lakin and Gleason', 23075, true);
insert into goods (id, name, description, price, in_stock) values (434, 'Elbertine', 'Ledner and Sons', 49565, true);
insert into goods (id, name, description, price, in_stock) values (435, 'Neala', 'Sawayn, Hodkiewicz and White', 10347, true);
insert into goods (id, name, description, price, in_stock) values (436, 'Brigitta', 'Ward-Barrows', 77933, true);
insert into goods (id, name, description, price, in_stock) values (437, 'Morgana', 'Walsh-Keeling', 57016, false);
insert into goods (id, name, description, price, in_stock) values (438, 'Daffi', 'Johns, Huel and Konopelski', 74232, false);
insert into goods (id, name, description, price, in_stock) values (439, 'Sallie', 'Wintheiser, Aufderhar and Beer', 86893, true);
insert into goods (id, name, description, price, in_stock) values (440, 'Leonelle', 'Rippin-Koepp', 24444, true);
insert into goods (id, name, description, price, in_stock) values (441, 'Samantha', 'Schneider, Wunsch and Wiza', 11340, true);
insert into goods (id, name, description, price, in_stock) values (442, 'Ruthie', 'Lind, Bode and Keeling', 96519, true);
insert into goods (id, name, description, price, in_stock) values (443, 'Clemmy', 'King, Schuppe and Jacobi', 21157, false);
insert into goods (id, name, description, price, in_stock) values (444, 'Adella', 'Treutel-Douglas', 2431, false);
insert into goods (id, name, description, price, in_stock) values (445, 'Jourdan', 'Pagac, Baumbach and Goyette', 78290, false);
insert into goods (id, name, description, price, in_stock) values (446, 'Devonna', 'Hickle LLC', 11176, true);
insert into goods (id, name, description, price, in_stock) values (447, 'Ailis', 'Rodriguez, Legros and Legros', 44616, true);
insert into goods (id, name, description, price, in_stock) values (448, 'Stepha', 'Daugherty-Pfannerstill', 24511, false);
insert into goods (id, name, description, price, in_stock) values (449, 'Roslyn', 'Hilll, Runolfsdottir and Gerhold', 76332, false);
insert into goods (id, name, description, price, in_stock) values (450, 'Dulcia', 'Blanda LLC', 41032, false);
insert into goods (id, name, description, price, in_stock) values (451, 'Bessy', 'Bahringer, Metz and Orn', 44932, true);
insert into goods (id, name, description, price, in_stock) values (452, 'Noelle', 'Jast LLC', 73326, false);
insert into goods (id, name, description, price, in_stock) values (453, 'Zola', 'O''Connell Group', 58214, true);
insert into goods (id, name, description, price, in_stock) values (454, 'Max', 'Kozey-Feil', 16491, false);
insert into goods (id, name, description, price, in_stock) values (455, 'Annabel', 'Ondricka Group', 16724, false);
insert into goods (id, name, description, price, in_stock) values (456, 'Christabel', 'Bayer-Moen', 25832, true);
insert into goods (id, name, description, price, in_stock) values (457, 'Analiese', 'Cronin-Schiller', 77339, false);
insert into goods (id, name, description, price, in_stock) values (458, 'Trudy', 'Wisozk-Medhurst', 31197, false);
insert into goods (id, name, description, price, in_stock) values (459, 'Dodi', 'Bogan and Sons', 17383, false);
insert into goods (id, name, description, price, in_stock) values (460, 'Paulita', 'Hintz Group', 94836, false);
insert into goods (id, name, description, price, in_stock) values (461, 'Debra', 'Maggio, Schroeder and Lindgren', 80677, true);
insert into goods (id, name, description, price, in_stock) values (462, 'Sondra', 'Bergstrom Group', 92506, true);
insert into goods (id, name, description, price, in_stock) values (463, 'Donelle', 'Zemlak-Kassulke', 16356, false);
insert into goods (id, name, description, price, in_stock) values (464, 'Christan', 'Grant, Marquardt and Schowalter', 7127, true);
insert into goods (id, name, description, price, in_stock) values (465, 'Patsy', 'Marquardt, Hoppe and McKenzie', 92057, true);
insert into goods (id, name, description, price, in_stock) values (466, 'Lissi', 'Pfannerstill Group', 9325, true);
insert into goods (id, name, description, price, in_stock) values (467, 'Lacey', 'Casper, Anderson and Sporer', 56496, false);
insert into goods (id, name, description, price, in_stock) values (468, 'Ermina', 'Heaney-Kunze', 68069, true);
insert into goods (id, name, description, price, in_stock) values (469, 'Elvera', 'Rolfson, Rowe and Yost', 22584, false);
insert into goods (id, name, description, price, in_stock) values (470, 'Karia', 'Kunze, Block and Terry', 92522, true);
insert into goods (id, name, description, price, in_stock) values (471, 'Valentia', 'Deckow, Lind and Fisher', 97205, true);
insert into goods (id, name, description, price, in_stock) values (472, 'Angelle', 'Hauck-Harber', 52674, true);
insert into goods (id, name, description, price, in_stock) values (473, 'Sharon', 'Conn-Skiles', 86795, true);
insert into goods (id, name, description, price, in_stock) values (474, 'Sadye', 'Greenfelder, Armstrong and Kirlin', 5186, true);
insert into goods (id, name, description, price, in_stock) values (475, 'Gerhardine', 'Bergstrom, Aufderhar and Klocko', 58870, true);
insert into goods (id, name, description, price, in_stock) values (476, 'Evelyn', 'Schowalter, Terry and Conn', 1148, true);
insert into goods (id, name, description, price, in_stock) values (477, 'Alyssa', 'Lindgren, Trantow and Davis', 69912, true);
insert into goods (id, name, description, price, in_stock) values (478, 'Alicia', 'Abbott-Dooley', 13073, false);
insert into goods (id, name, description, price, in_stock) values (479, 'Gussy', 'Oberbrunner, Kub and Bahringer', 28908, true);
insert into goods (id, name, description, price, in_stock) values (480, 'Lucita', 'Reynolds, Conn and Klein', 74021, false);
insert into goods (id, name, description, price, in_stock) values (481, 'Manya', 'Wyman LLC', 29562, true);
insert into goods (id, name, description, price, in_stock) values (482, 'Colly', 'Glover Inc', 62641, false);
insert into goods (id, name, description, price, in_stock) values (483, 'Rennie', 'Kuhic, Casper and Rempel', 76066, true);
insert into goods (id, name, description, price, in_stock) values (484, 'Ofelia', 'Schneider, Gerhold and Kreiger', 17969, false);
insert into goods (id, name, description, price, in_stock) values (485, 'Nancy', 'Predovic-Larkin', 48156, true);
insert into goods (id, name, description, price, in_stock) values (486, 'Angelia', 'Dooley-Conroy', 19393, true);
insert into goods (id, name, description, price, in_stock) values (487, 'Crystie', 'Reilly, Corwin and Auer', 34716, false);
insert into goods (id, name, description, price, in_stock) values (488, 'Maryellen', 'Marquardt-Schimmel', 59637, true);
insert into goods (id, name, description, price, in_stock) values (489, 'Cordelie', 'Hoppe-Douglas', 89420, true);
insert into goods (id, name, description, price, in_stock) values (490, 'Diandra', 'Skiles Group', 90659, true);
insert into goods (id, name, description, price, in_stock) values (491, 'Audrie', 'Koch Inc', 1987, true);
insert into goods (id, name, description, price, in_stock) values (492, 'Stepha', 'Pfannerstill and Sons', 34174, true);
insert into goods (id, name, description, price, in_stock) values (493, 'Trixi', 'Hodkiewicz Inc', 46005, true);
insert into goods (id, name, description, price, in_stock) values (494, 'Fiona', 'Ward-Watsica', 1171, false);
insert into goods (id, name, description, price, in_stock) values (495, 'Alexa', 'Larson LLC', 58294, true);
insert into goods (id, name, description, price, in_stock) values (496, 'Jaclin', 'Simonis, Luettgen and Beahan', 89118, true);
insert into goods (id, name, description, price, in_stock) values (497, 'Clarabelle', 'Prosacco-Howe', 67941, false);
insert into goods (id, name, description, price, in_stock) values (498, 'Wilma', 'Franecki-Mante', 29765, true);
insert into goods (id, name, description, price, in_stock) values (499, 'Gladi', 'Nienow-Stanton', 78685, true);
insert into goods (id, name, description, price, in_stock) values (500, 'Eadie', 'Olson, Ullrich and Metz', 84211, true);
